version: "3.8"
services:
  jupyterlab:
    build: 
      context: container
      args:
        REQUIREMENTS: ${REQUIREMENTS}
        GIT_NAME: ${GIT_NAME}
        GIT_MAIL: ${GIT_MAIL}
        GITHUB_CREDENTIAL: ${GITHUB_CREDENTIAL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    volumes:
      - ".jupyter:/root/.jupyter"
      - "./container/credential:/usr/share/doc/git/contrib/credential"
      - "${DATASET_LOCALDIR}:${DATASET_DIR}"
      - ".:/workspace"
    env_file: container/.env
    
    command: python3 -m jupyter lab --ip=0.0.0.0 --allow-root
    ports:
      - 8888:8888
